name: Quick Blog Post
description: Just give a topic - AI generates the title and everything else
title: "[Blog] "
labels: ["blog"]
body:
  - type: markdown
    attributes:
      value: |
        ## Quick Blog Post
        Just give a topic idea. Claude will generate the title, pick a category, write the full article, and publish it with a backdated date.

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What should the blog post be about? Just a sentence or two is fine.
      placeholder: "e.g., dealing with last-minute schedule changes from your co-parent"
    validations:
      required: true
