name: Quick Blog Post
description: Just give a topic - AI generates the title and everything else
title: "[Blog] New Post"
labels: ["blog"]
body:
  - type: markdown
    attributes:
      value: |
        ## Quick Blog Post
        Just fill in the Topic below and click Create. Ignore the title field above - Claude generates the actual blog title.

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What should the blog post be about? Just a sentence or two is fine.
      placeholder: "e.g., dealing with last-minute schedule changes from your co-parent"
    validations:
      required: true
