#!/usr/bin/env node
/*
 * seo-check.js — technical-SEO regression guard (round 1).
 *
 * Pure static analysis of committed files. No network, no Notion, no build
 * step required, so it runs anywhere (locally, CI, Netlify) and never alters
 * page content. Exits non-zero on any violation so the build/test fails loudly.
 *
 * Checks:
 *   1. Every application/ld+json block on every page is valid JSON.
 *   2. No JSON-LD uses a known-invalid schema.org @type (denylist).
 *   3. Hand-authored pages have exactly one absolute, https canonical.
 *   4. JSON-LD image/logo URLs on hand-authored pages are absolute
 *      (Google ignores relative image/logo URLs in structured data).
 *   5. No URL listed in sitemap.xml is the "from" side of a 301/302 redirect
 *      declared in netlify.toml (redirected URLs must not be in the sitemap).
 *
 * Note on scope: blog/*.html are BUILD ARTIFACTS generated by build-blog.js
 * from Notion. Their source of truth is the generator template, which already
 * emits absolute URLs. So checks 3 & 4 (canonical/absolute-URL) skip blog/*.html
 * to avoid failing on stale committed artifacts; check 1 & 2 still cover them.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ORIGIN = 'https://getclearly.app';

// schema.org @type values we know are invalid / not in the vocabulary.
// Extend as needed — this is a regression guard, not a full validator.
const INVALID_TYPES = new Set(['Guide']);

const errors = [];
const warnings = [];

// ---- collect HTML files (skip vendored / archived / build dirs) --------------
function walk(dir, acc) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    if (['node_modules', '_archive', '_partials', 'docs'].includes(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, acc);
    else if (entry.name.endsWith('.html')) acc.push(full);
  }
  return acc;
}
const htmlFiles = walk(ROOT, []);

function rel(file) {
  return path.relative(ROOT, file);
}
function isBlogPost(file) {
  return rel(file).startsWith('blog/') && rel(file) !== 'blog.html';
}

// ---- extract every JSON-LD block from a page ---------------------------------
function extractJsonLd(html) {
  const blocks = [];
  const re = /<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(html)) !== null) blocks.push(m[1].trim());
  return blocks;
}

// ---- recursively collect all @type values in a parsed JSON-LD object ---------
function collectTypes(node, out) {
  if (Array.isArray(node)) {
    node.forEach((n) => collectTypes(n, out));
  } else if (node && typeof node === 'object') {
    if (node['@type']) {
      const t = node['@type'];
      (Array.isArray(t) ? t : [t]).forEach((v) => out.add(v));
    }
    Object.values(node).forEach((v) => collectTypes(v, out));
  }
  return out;
}

// ---- 1 & 2: JSON-LD validity + invalid-type denylist (all pages) -------------
for (const file of htmlFiles) {
  const html = fs.readFileSync(file, 'utf-8');
  const blocks = extractJsonLd(html);
  blocks.forEach((block, i) => {
    let parsed;
    try {
      parsed = JSON.parse(block);
    } catch (e) {
      errors.push(`${rel(file)}: JSON-LD block #${i + 1} is invalid JSON — ${e.message}`);
      return;
    }
    const types = collectTypes(parsed, new Set());
    for (const t of types) {
      if (INVALID_TYPES.has(t)) {
        errors.push(`${rel(file)}: JSON-LD uses invalid schema.org @type "${t}"`);
      }
    }
  });
}

// ---- 3 & 4: canonical + absolute image/logo URLs (hand-authored pages) -------
for (const file of htmlFiles) {
  if (isBlogPost(file)) continue; // generated artifact — see header note
  if (rel(file) === '404.html') continue; // error page: no canonical expected
  const html = fs.readFileSync(file, 'utf-8');

  // exactly one absolute https canonical
  const canon = [...html.matchAll(/<link[^>]+rel=["']canonical["'][^>]*>/gi)];
  if (canon.length === 0) {
    warnings.push(`${rel(file)}: no <link rel="canonical">`);
  } else if (canon.length > 1) {
    errors.push(`${rel(file)}: ${canon.length} canonical tags (expected 1)`);
  } else {
    const href = (canon[0][0].match(/href=["']([^"']+)["']/i) || [])[1] || '';
    if (!href.startsWith('https://')) {
      errors.push(`${rel(file)}: canonical is not an absolute https URL — "${href}"`);
    }
  }

  // relative image/logo/url inside JSON-LD → not allowed
  for (const block of extractJsonLd(html)) {
    const relRefs = block.match(/"(?:image|logo|url)":\s*"\/[^"]*\.(?:png|jpg|jpeg|webp|svg|gif)"/gi);
    if (relRefs) {
      for (const r of relRefs) {
        errors.push(`${rel(file)}: relative image/logo URL in JSON-LD — ${r} (must be absolute)`);
      }
    }
  }
}

// ---- 5: no redirected URL appears in sitemap.xml -----------------------------
function parseRedirectSources(toml) {
  // crude [[redirects]] block parser; good enough for netlify.toml
  const sources = [];
  const blocks = toml.split(/\[\[redirects\]\]/).slice(1);
  for (const b of blocks) {
    const from = (b.match(/from\s*=\s*"([^"]+)"/) || [])[1];
    const status = (b.match(/status\s*=\s*(\d+)/) || [])[1];
    if (!from || !status) continue;
    if (!['301', '302', '308', '307'].includes(status)) continue;
    if (!from.startsWith('/')) continue; // skip full-URL host redirects
    if (from.includes('*')) continue; // skip catch-alls (e.g. /*)
    // Compare exact paths. A "/x" -> "/x/" trailing-slash redirect must NOT
    // match the sitemap's canonical "/x/" target, so do not normalise slashes.
    sources.push(from);
  }
  return sources;
}

try {
  const sitemap = fs.readFileSync(path.join(ROOT, 'sitemap.xml'), 'utf-8');
  const toml = fs.readFileSync(path.join(ROOT, 'netlify.toml'), 'utf-8');
  const redirectSources = new Set(parseRedirectSources(toml));
  const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim());
  for (const loc of locs) {
    const p = loc.replace(ORIGIN, '') || '/';
    if (redirectSources.has(p)) {
      errors.push(`sitemap.xml: lists ${loc} which is a redirect source in netlify.toml`);
    }
  }
} catch (e) {
  errors.push(`Could not check sitemap/redirects: ${e.message}`);
}

// ---- report ------------------------------------------------------------------
if (warnings.length) {
  console.log(`\nSEO check — ${warnings.length} warning(s):`);
  warnings.forEach((w) => console.log(`  ⚠ ${w}`));
}
if (errors.length) {
  console.error(`\nSEO check FAILED — ${errors.length} error(s):`);
  errors.forEach((e) => console.error(`  ✗ ${e}`));
  process.exit(1);
}
console.log(`\nSEO check passed: ${htmlFiles.length} HTML files, JSON-LD valid, canonicals absolute, no redirected URLs in sitemap.`);
